export const USER_ACTION_TYPES = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGNIN_WITH_GOOGLE_START: "SIGNIN_WITH_GOOGLE_START",
  SIGNIN_WITH_EMAIL_START: "SIGNIN_WITH_EMAIL_START",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  SIGNOUT_START: "SIGNOUT_START",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILED: "SIGNOUT_FAILED",
};
