export const USER_ACTION_TYPES = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGNIN_WITH_GOOGLE: "SIGNIN_WITH_GOOGLE",
  SIGNIN_WITH_EMAIL: "SIGNIN_WITH_EMAIL",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILED: "SIGNIN_FAILED",
};
